### ISSUE TITLE
Any workaround available?

### ISSUE THREAD

**Issue by gongzhang** [RemiBardon/xcode-preview-spm-resources-bug#2]
Hi, Rémi Bardon,
Thanks for providing the clear description of the bug. I ran into the same problem. Do you have any good workaround for this?

**Comment by RemiBardon** [comment]
Yes I do. It's https://github.com/RemiBardon/xcode-preview-spm-resources-bug/commit/6599c31af1c49fe884e2b84149043aee51aca031 on the [workaround](https://github.com/RemiBardon/xcode-preview-spm-resources-bug/tree/workaround) branch 😉

**Comment by gongzhang** [comment]
@RemiBardon Works like magic! 🎉 😎 Thank you.

**Comment by RemiBardon** [comment]
You're welcome 😉
